# Generated by Django 5.2.7 on 2025-11-06 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locked', models.BooleanField()),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_address', models.TextField(blank=True, null=True)),
                ('contact_phone', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('style', models.CharField(max_length=200)),
                ('number_artists', models.PositiveSmallIntegerField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('todo_sent_cfa', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timestamp', models.DateTimeField()),
                ('agreement', models.TextField(blank=True, null=True)),
                ('todo_gema', models.BooleanField()),
                ('todo_got_setlist', models.BooleanField()),
                ('todo_got_invoice', models.BooleanField()),
                ('todo_gema_setlist', models.BooleanField()),
                ('required_free_tickets', models.PositiveSmallIntegerField()),
                ('required_paid_tickets', models.PositiveSmallIntegerField()),
                ('booked_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artistboard.artist')),
            ],
        ),
        migrations.CreateModel(
            name='EventArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artistboard.artist')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artistboard.event')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artistboard.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artistboard.season')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artistboard.show'),
        ),
    ]
