# Generated by Django 5.2.7 on 2025-11-08 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='start_timestamp',
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 8, 11, 47, 42, 176356), verbose_name='Starts on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default='00:00', verbose_name='Starts at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='todo_gema',
            field=models.BooleanField(verbose_name='Created GEMA event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='todo_gema_setlist',
            field=models.BooleanField(verbose_name='Sent setlist to GEMA'),
        ),
        migrations.AlterField(
            model_name='event',
            name='todo_got_invoice',
            field=models.BooleanField(verbose_name='Got invoice from artist'),
        ),
        migrations.AlterField(
            model_name='event',
            name='todo_got_setlist',
            field=models.BooleanField(verbose_name='Got setlist from artist'),
        ),
        migrations.AlterField(
            model_name='season',
            name='todo_sent_cfa',
            field=models.BooleanField(verbose_name='Sent CfA'),
        ),
    ]
