# Generated by Django 5.2.7 on 2025-11-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistboard', '0002_remove_event_start_timestamp_event_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='required_free_tickets',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='required_paid_tickets',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='todo_gema',
            field=models.BooleanField(default=False, verbose_name='Created GEMA event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='todo_gema_setlist',
            field=models.BooleanField(default=False, verbose_name='Sent setlist to GEMA'),
        ),
        migrations.AlterField(
            model_name='event',
            name='todo_got_invoice',
            field=models.BooleanField(default=False, verbose_name='Got invoice from artist'),
        ),
        migrations.AlterField(
            model_name='event',
            name='todo_got_setlist',
            field=models.BooleanField(default=False, verbose_name='Got setlist from artist'),
        ),
    ]
