# Generated by Django 5.2.7 on 2025-11-08 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistboard', '0003_alter_event_required_free_tickets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='booked_artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artistboard.artist'),
        ),
    ]
