# Generated by Django 5.2.7 on 2025-11-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistboard', '0005_alter_artist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
