# Generated by Django 5.2.7 on 2025-11-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistboard', '0006_alter_artist_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='number_artists',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
