# Generated by Django 5.2.7 on 2025-11-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistboard', '0007_alter_artist_number_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='number_artists',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='style',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
