# Generated by Django 5.2.7 on 2025-11-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistboard', '0008_alter_artist_number_artists_alter_artist_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('single_season', 'Single season'), ('all_artists', 'All artists'), ('single_artist', 'Single artist')])),
                ('subject', models.TextField()),
                ('to', models.TextField()),
                ('cc', models.TextField(blank=True, null=True)),
                ('bcc', models.TextField(blank=True, null=True)),
                ('body_text', models.TextField(blank=True, null=True)),
                ('body_html', models.TextField(blank=True, null=True)),
                ('use_markdown', models.BooleanField(default=False)),
            ],
        ),
    ]
