# Generated by Django 5.2.7 on 2025-11-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistboard', '0009_mailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, help_text='Rating of 5 stars', null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.CharField(choices=[('website', 'Website'), ('fediverse', 'Fediverse'), ('instagram', 'Instagram'), ('youtube', 'Youtube'), ('facebook', 'Facebook'), ('bandcamp', 'Bandcamp'), ('soundcloud', 'Soundcloud')], max_length=200),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='body_html',
            field=models.TextField(blank=True, null=True, verbose_name='Body (HTML)'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='body_text',
            field=models.TextField(blank=True, null=True, verbose_name='Body (Text)'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='type',
            field=models.CharField(choices=[('single_season', 'Single season'), ('all_artists', 'All artists'), ('single_artist', 'Single artist')], help_text='Single season will get a context of season, shows, events. All Artists will get the context artists. Single artist will get the context artist.'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='use_markdown',
            field=models.BooleanField(default=False, help_text='Use the markdown rendered version of the text body for the HTML body'),
        ),
    ]
