# Generated by Django 5.2.7 on 2025-11-19 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistboard', '0010_artist_rating_alter_link_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('available_for', models.CharField(choices=[('season', 'Season'), ('event', 'Event')])),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='todo_gema',
        ),
        migrations.RemoveField(
            model_name='event',
            name='todo_gema_setlist',
        ),
        migrations.RemoveField(
            model_name='event',
            name='todo_got_invoice',
        ),
        migrations.RemoveField(
            model_name='event',
            name='todo_got_setlist',
        ),
        migrations.RemoveField(
            model_name='season',
            name='todo_sent_cfa',
        ),
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.CharField(choices=[('website', 'Website'), ('fediverse', 'Fediverse'), ('instagram', 'Instagram'), ('youtube', 'Youtube'), ('facebook', 'Facebook'), ('bandcamp', 'Bandcamp'), ('soundcloud', 'Soundcloud'), ('twitch', 'Twitch'), ('spotify', 'Spotify')], max_length=200),
        ),
        migrations.CreateModel(
            name='SeasonTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artistboard.season')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artistboard.todo')),
            ],
        ),
        migrations.CreateModel(
            name='EventTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artistboard.event')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artistboard.todo')),
            ],
        ),
    ]
