# Generated by Django 6.0.2 on 2026-02-18 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistboard', '0011_todo_remove_event_todo_gema_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Artist', 'verbose_name_plural': 'Artists'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventartist',
            options={'verbose_name': 'Opportunity', 'verbose_name_plural': 'Opportunities'},
        ),
        migrations.AlterModelOptions(
            name='eventtodo',
            options={'verbose_name': 'Event Todo', 'verbose_name_plural': 'Event Todos'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Link', 'verbose_name_plural': 'Links'},
        ),
        migrations.AlterModelOptions(
            name='mailtemplate',
            options={'verbose_name': 'Mail template', 'verbose_name_plural': 'Mail templates'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'verbose_name': 'Season', 'verbose_name_plural': 'Seasons'},
        ),
        migrations.AlterModelOptions(
            name='seasontodo',
            options={'verbose_name': 'Season Todo', 'verbose_name_plural': 'Season Todos'},
        ),
        migrations.AlterModelOptions(
            name='show',
            options={'verbose_name': 'Show', 'verbose_name_plural': 'Shows'},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'Todo', 'verbose_name_plural': 'Todos'},
        ),
        migrations.AlterField(
            model_name='artist',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='contact_address',
            field=models.TextField(blank=True, null=True, verbose_name='Contact address'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='contact_email',
            field=models.EmailField(max_length=254, verbose_name='Contact E-Mail'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='contact_name',
            field=models.CharField(max_length=200, verbose_name='Contact name'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Contact phone'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Artist info'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='locked',
            field=models.BooleanField(verbose_name='Locked'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='number_artists',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Number of artists'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, help_text='Rating of 5 stars', null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='style',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Style'),
        ),
        migrations.AlterField(
            model_name='event',
            name='agreement',
            field=models.TextField(blank=True, null=True, verbose_name='Agreement'),
        ),
        migrations.AlterField(
            model_name='event',
            name='booked_artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artistboard.artist', verbose_name='Booked Artist'),
        ),
        migrations.AlterField(
            model_name='event',
            name='required_free_tickets',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Required free tickets'),
        ),
        migrations.AlterField(
            model_name='event',
            name='required_paid_tickets',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Required paid tickets'),
        ),
        migrations.AlterField(
            model_name='event',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artistboard.show', verbose_name='Show'),
        ),
        migrations.AlterField(
            model_name='eventartist',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artistboard.artist', verbose_name='Artist'),
        ),
        migrations.AlterField(
            model_name='eventartist',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artistboard.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='eventtodo',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Done'),
        ),
        migrations.AlterField(
            model_name='eventtodo',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artistboard.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='eventtodo',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artistboard.todo', verbose_name='Todo'),
        ),
        migrations.AlterField(
            model_name='link',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artistboard.artist', verbose_name='Artist'),
        ),
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.CharField(choices=[('website', 'Website'), ('fediverse', 'Fediverse'), ('instagram', 'Instagram'), ('youtube', 'Youtube'), ('facebook', 'Facebook'), ('bandcamp', 'Bandcamp'), ('soundcloud', 'Soundcloud'), ('twitch', 'Twitch'), ('spotify', 'Spotify')], max_length=200, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='bcc',
            field=models.TextField(blank=True, null=True, verbose_name='BCC'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='cc',
            field=models.TextField(blank=True, null=True, verbose_name='CC'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='subject',
            field=models.TextField(verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='to',
            field=models.TextField(verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='type',
            field=models.CharField(choices=[('single_season', 'Single season'), ('all_artists', 'All artists'), ('single_artist', 'Single artist')], help_text='Single season will get a context of season, shows, events, artists. All Artists will get the context artists. Single artist will get the context artist, booked_events, unbooked_events and last_season.', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='use_markdown',
            field=models.BooleanField(default=False, help_text='Use the markdown rendered version of the text body for the HTML body', verbose_name='Use markdown'),
        ),
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.PositiveSmallIntegerField(verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='seasontodo',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Done'),
        ),
        migrations.AlterField(
            model_name='seasontodo',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artistboard.season', verbose_name='Season'),
        ),
        migrations.AlterField(
            model_name='seasontodo',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artistboard.todo', verbose_name='Todo'),
        ),
        migrations.AlterField(
            model_name='show',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='show',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artistboard.season', verbose_name='Season'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='available_for',
            field=models.CharField(choices=[('season', 'Season'), ('event', 'Event')], verbose_name='Available for'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo',
            field=models.CharField(max_length=200, verbose_name='Todo'),
        ),
    ]
