# Generated by Django 6.0.2 on 2026-02-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistboard', '0012_alter_artist_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='type',
            field=models.CharField(choices=[('single_season', 'Single season'), ('all_artists', 'All artists'), ('single_artist', 'Single artist'), ('single_event', 'Single event')], help_text='Single season will get a context of season, shows, events, artists. All Artists will get the context artists. Single artist will get the context artist, booked_events, unbooked_events and last_season. Single event will get the context event.', verbose_name='Type'),
        ),
    ]
